### ISSUE TITLE
RunCreateBeelineScenario / ConfigAddUAMParameters Function doesn't work since Upgrade to MATSim ver12

### ISSUE THREAD

**Issue by tnt456** [BauhausLuftfahrt/MATSim-UAM#60]
Hey, 
I am trying to create a scenario with UAM from an existing MATSim Scenario, so I wanted to Run the RunCreateBeelineScenario method within the UAM Package. It seems to me, that the ConfigAddUAMParameters method which is called is not updated to go with the newest updates in the UAMConfiggroup because i get the Error that ie. the parameter inputUAMFile is not supported anymore. Are there any Works done or planned on that? 
Greetings
Tobias

**Comment by balacmi** [comment]
Hi Tobias,

I made a lot of changes last night with a pull request that should solve that issue. Can you tell if it works?

Best,
Milos

**Comment by tnt456** [comment]
Hey I finally had the time to try it, and now it works as expected again! 
Thank you :)
