### ISSUE TITLE
Replace Bintray (out-of-service) with other service

### ISSUE THREAD

**Issue by RRothfeld** [BauhausLuftfahrt/MATSim-UAM#70]
Bintray has closed down. Find other service to make MATSim-UAM available through Maven.

**Comment by balacmi** [comment]
Were we putting anything on bintray? I thought everything was based on jitpack?

Of course we need to change matsim repo as that changed with bintray dying.

**Comment by RRothfeld** [comment]
You are right, we are not using Bintray - jitpack still works. I got confused.
