### ISSUE TITLE
uam-test-scenario not working for uam 4.1.2

### ISSUE THREAD

**Issue by markusstraub** [BauhausLuftfahrt/MATSim-UAM#91]
The `uam-test-scenario` was not upgraded properly and does not work now. It only requires a few changes to `uam_config.xml` and `uam_vehicles.xml`.

The fixed version: [uam-test-scenario.tar.gz](https://github.com/BauhausLuftfahrt/MATSim-UAM/files/11677297/uam-test-scenario.tar.gz)

**Comment by RRothfeld** [comment]
Thank you, Markus, this should be fixed with commit ab8e2f6.

**Comment by RRothfeld** [comment]
Thank you, Markus, this should be fixed with commit https://github.com/BauhausLuftfahrt/MATSim-UAM/commit/ab8e2f60babf02cf9ad1929da39cf6764a5f8dc9.
